CREATE TABLE BILL(
    IDBILL      UNIQUEIDENTIFIER    NOT NULL PRIMARY KEY,
    NAME        NVARCHAR(200)       NOT NULL,
    DATE        DATE                NOT NULL,
    VALUE       DECIMAL(18,2)       NOT NULL,
    IDCATEGORY  UNIQUEIDENTIFIER    NOT NULL,
    TYPE        INT                 NOT NULL,
    OBSERVATION NVARCHAR(350)       NOT NULL,
    IDUSER      UNIQUEIDENTIFIER    NOT NULL,
    IDCATEGORY  UNIQUEIDENTIFIER    NOT NULL,

    FOREIGN KEY (IDCATEGORY) REFERENCES CATEGORY(IDCATEGORY),
    FOREIGN KEY (IDUSER) REFERENCES USERREGISTER(IDUSER),

)

CREATE TABLE CATEGORY(
    IDCATEGORY  UNIQUEIDENTIFIER    NOT NULL PRIMARY KEY,
    NAME        NVARCHAR(200)       NOT NULL,
    IDUSER   UNIQUEIDENTIFIER    NOT NULL,

    FOREIGN KEY(IDUSER) REFERENCES USERREGISTER (IDUSER)
)

select * from category
