CREATE TABLE USERREGISTER(
		IDUSER				UNIQUEIDENTIFIER	NOT NULL,
		NAME				NVARCHAR(150)		NOT NULL,
		EMAIL				NVARCHAR(100)		NOT NULL UNIQUE,
		PASSOWRD			NVARCHAR(20)		NOT NULL,
		DATETIMECRIATION	DATETIME			NOT NULL,

		PRIMARY KEY(IDUSER)

)
GO

DROP TABLE USUARIO

SELECT * FROM USUARIO